# Generated by Django 4.0.3 on 2022-04-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiempo', models.CharField(max_length=50)),
                ('Distancia', models.CharField(max_length=50)),
                ('Velocidad', models.CharField(max_length=50)),
                ('Aceleracion', models.CharField(max_length=50)),
            ],
        ),
    ]
