# Generated by Django 4.0.3 on 2022-04-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graficacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distancia',
            old_name='Distancia',
            new_name='Posicion',
        ),
    ]
